version: '3.8'

services:
  php-fpm:
    image: php:8.2-fpm
    container_name: php-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    networks:
      - backend
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./app/public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - php-fpm

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
