services:
  php-fpm:
    image: php:8.2-fpm
    container_name: php-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini  
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - php-fpm

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:  
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
