version: '3.8'

services:
  php-fpm:
    build: .
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - backend
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./app/public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - backend
    depends_on:
      - php-fpm

networks:
  backend:
    driver: bridge
